sudo: false
go_import_path: github.com/go-latex/latex

language: go

go:
 - 1.14.x
 - 1.13.x
 - master

os:
 - linux
 - osx
 - windows

arch:
 - amd64
 - arm64

env:
 global:
  - GO111MODULE=on
  - GOFLAGS="-mod=readonly"

cache:
 directories:
  - $HOME/.cache/go-build
  - $HOME/gopath/pkg/mod

git:
 depth: 1
 autocrlf: input

matrix:
 fast_finish: true
 allow_failures:
  - go: master
